### ISSUE TITLE
fix path error: workflow basedir parent is repo

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/reference-container#2]
In `functions` module, line 42
```   
 repo_path = pl.Path(workflow.basedir).absolute()
```

**Comment by svenwillger** [comment]
In `functions` module, line 68(!) code changed to:
```
repo_path = pl.Path(workflow.basedir).parent.resolve(strict=True)
```
commit hash: 
`fix in functions module: repo_path`

**Comment by ptrebert** [comment]
indeed, I put the wrong line there, sorry.

one request: please add the commit hash that fixed the issue in the closing message
