### ISSUE TITLE
Add information regarding possible other reasons for "No 'metadata_' keys in config..." error

### ISSUE THREAD

**Issue by svenwillger** [core-unit-bioinformatics/reference-container#5]
The error for "if not refcon_md" would also be thrown if the config file is missing the key "metadata_" or refcon_md is empty for another reason. This could be clarified if necessary.

https://github.com/core-unit-bioinformatics/reference-container/blob/2bf3de65ea13b7deed4cf13dedc8d6f8bd97ec55/workflow/rules/functions.smk#L32-L36

**Comment by ptrebert** [comment]
what about this one?

**Comment by svenwillger** [comment]
Since the error could only occur if we introduced it or something is broken that causes an empty 'refcon_md' I added a sentence to contact the developers if the user is sure they did everything right.

```
raise ValueError(
            "\nPotential user error:\n"
            "No 'metadata_' keys found in config. Did you forget to load a reference container config?\n"
            "You must specify the container configuration files via Snakemake's '--configfiles' option.\n\n"
            "If you are sure the container configuration file(s) with the 'metadata_' key word is/are present\n please contact the developers.\n\n"
        )
```

The commit comment is "Update to resolve issue #5"
